### ISSUE TITLE
AttributeError: module 'desloppify.engine.planning' has no attribute 'generate_issues

### ISSUE THREAD

**Issue by ltrottier-yelp** [peteromallet/desloppify#384]
Hello,

Using 
```
desloppify                         0.9.5
```

I got this issue:
```bash
$ desloppify scan

Desloppify Scan (python)

Traceback (most recent call last):
  File "/nail/home/ltrottier/model_benchmark/virtualenv_run/bin/desloppify", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nail/home/ltrottier/model_benchmark/virtualenv_run/lib/python3.11/site-packages/desloppify/cli.py", line 191, in main
    handler(args)
  File "/nail/home/ltrottier/model_benchmark/virtualenv_run/lib/python3.11/site-packages/desloppify/app/commands/scan/cmd.py", line 144, in cmd_scan
    issues, potentials, codebase_metrics = orchestrator.generate()
                                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/nail/home/ltrottier/model_benchmark/virtualenv_run/lib/python3.11/site-packages/desloppify/app/commands/scan/orchestrator.py", line 50, in generate
    return self.run_scan_generation_fn(self.runtime)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nail/home/ltrottier/model_benchmark/virtualenv_run/lib/python3.11/site-packages/desloppify/app/commands/scan/workflow.py", line 346, in run_scan_generation
    issues, potentials = plan_mod.generate_issues(
                         ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'desloppify.engine.planning' has no attribute 'generate_issues'
```

**Comment by peteromallet** [comment]
Fix incoming, apologies

**Comment by ltrottier-yelp** [comment]
Thanks, no worries. It works on 0.9.4.

**Comment by peteromallet** [comment]
This was a regression introduced in 0.9.5 — `workflow.py` referenced `plan_mod.generate_issues()` via the `planning` package, but `planning/__init__.py` doesn't (and shouldn't) export `generate_issues`.

Fixed on the `0.9.5` branch by importing directly from the submodule:

```python
from desloppify.engine.planning.scan import PlanScanOptions, generate_issues as generate_plan_issues
```

Will be included in the next patch release.

**Comment by peteromallet** [comment]
This is fixed in the latest push to `0.9.5`. The scan workflow was using an indirect `plan_mod.generate_issues` import path that broke when the planning module was restructured. The import now goes directly to `desloppify.engine.planning.scan.generate_issues`.

Please update to the latest `0.9.5` and let us know if this resolves it for you!

**Comment by paperbenni** [comment]
Not fixed in uvx desloppify
